Models/Book.cs
using System.ComponentModel.DataAnnotations; 

namespace Books_Inbox.Models
{
    public class Book
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string WriterName { get; set; }

        public int PageCount { get; set; }

        public string ImageName { get; set; }

        public DateTime DataTime { get; set; }    
        }

}

Models/BookDetailViewModel.cs
using Books_Inbox.Models;
public class BookDetailViewModel
{
    public Writer Writer { get; set; }
    public Book Book { get; set; }
}

Models/ErrorViewModel.cs
namespace Books_Inbox.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Writer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Books_Inbox.Models
{
    public class Writer
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        public string ImageName { get; set; }
        public DateTime BrithDataTime { get; set; }    
        public DateTime DeathDataTime { get; set; }    
        }

}

Models/WriterViewModel.cs
using Books_Inbox.Models;
public class WriterDetailViewModel
{
    public Writer Writer { get; set; }
    public Book Book { get; set; }
}

Controllers/BookController.cs
using Books_Inbox.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Books_Inbox.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _db;

        public BookController(ApplicationDbContext db)
        {
            _db = db;
        }


        public ActionResult Index()
        {
            IEnumerable<Book> objBookList = _db.Books.ToList();
            return View(objBookList);
        }
        public IActionResult Detail(int id)
        {
            var book = _db.Books.FirstOrDefault(p => p.ID == id);

            if (book == null)
                return NotFound();

            var Writer = _db.Writers.FirstOrDefault(c => c.Name == book.WriterName);
  

            var viewModel = new BookDetailViewModel
            {
                Writer = Writer,
                Book = book
            };
            return View(viewModel);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using Books_Inbox.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Books_Inbox.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult ContactUs()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/WriterController.cs
using Books_Inbox.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Books_Inbox.Controllers
{
    public class WriterController : Controller
    {
        private readonly ApplicationDbContext _db;

        public WriterController(ApplicationDbContext db)
        {
            _db = db;
        }


        public ActionResult Index()
        {
            IEnumerable<Writer> objWriterList = _db.Writers.ToList();
            return View(objWriterList);
        }
        public IActionResult Detail(int id)
        {
            var writer = _db.Writers.FirstOrDefault(p => p.ID == id);

            if (writer == null)
                return NotFound();

            var book = _db.Books.FirstOrDefault(c => c.WriterName == writer.Name);

            //if (Writer == null)
            //    return NotFound(); // Handle the case where the category is not found

            var viewModel = new WriterDetailViewModel
            {
                Writer = writer,
                Book = book
            };
            return View(viewModel);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Book/Detail.cshtml
@model BookDetailViewModel

@{
    ViewData["Title"] = @Model.Book.Name;
    <link rel="stylesheet" href="~/css/booksStyle.css" />
    <link rel="stylesheet" href="~/css/sliderStyle.css" />
    <link rel="stylesheet" href="~/css/footerStyle.css" />
}
<br>
<br>
<div class="border p-3 mt-4">
    <h1>@Model.Book.Name </h1>

    <div class="row">
        <div>
            <img src="@Url.Content("~/img/" +@Model.Book.ImageName)" alt="Kitap foto" class="card-img viewimg">
        </div>
        <ul class="list-unstyled">
            <div> Ad : @Model.Book.Name </div>
            <br>
            <div>
                @if (@Model.Writer != null)
                {
                    <p> Yazar : <button class="ViewBtn"><a asp-controller="Writer" asp-action="Detail"
                                asp-route-id="@Model.Writer.ID">@Model.Book.WriterName</a></button></p>
                }
                else
                {
                    <p> Yazar : <button class="ViewBtn">@Model.Book.WriterName</button></p>
                }
                <br>
                <p>Çıkış Tarihi: @Model.Book.DataTime.Year </p>
                <br>
                <p>Sayfa Sayısı: @Model.Book.PageCount </p>
            </div>
            <a asp-controller="Book" asp-action="Index"><button class="ViewBtn">Geri</button></a>
        </ul>
    </div><br><br><br><br><br><br><br><br><br>

Views/Book/Index.cshtml
@model IEnumerable<Book>
@{
    ViewData["Title"] = "Kitaplar";
  
    <link rel="stylesheet" href="~/css/booksStyle.css" />
    <link rel="stylesheet" href="~/css/sliderStyle.css" />
    <link rel="stylesheet" href="~/css/swiper-bundle.min.css">
}

 <!--Body1-->
    <div class="books-body-1">
        <div class="books-yazi-1">Öne Çıkan Kitaplar</div>
    </div>


    <!--slider-->
    <div class="slide-container swiper">
        <div class="slide-content">
            <div class="card-wrapper swiper-wrapper">
                <!--#region card swiper-slides  -->
                <!--01-->
                @foreach (var obj in Model)
                {
                    <div class="card swiper-slide">
                    <div class="image-content">
                        <span class="overlay"></span>
                        <div class="card-image">
                            <img src="@Url.Content("~/img/" +@obj.ImageName)" alt="Book Image" class="card-img">
                        </div>
                    </div>
                    <div class="card-content">
                        <h5 class="name">@obj.Name</h5>
                        <h6 class="descreption">@obj.WriterName</h6>
                        <button class="ViewBtn"> <a asp-controller="Book" asp-action="Detail" asp-route-id="@obj.ID">Görüntüle</a></button>
                    </div>
                </div>
                }
                

                <!-- endregion -->


            </div>
        </div>
        <div class="swiper-button-next swiper-navBtn"></div>
        <div class="swiper-button-prev swiper-navBtn"></div>
        <div class="swiper-pagination"></div>
    </div>


    <script src="../js/swiper-bundle.min.js"></script>

Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "Hakkımzda";
    <link rel="stylesheet" href="~/css/aboutusStyle.css" />
}


<div class="aboutus-page">
    <div class="aboutusBg">
        <img src="~/img/AboutusBg.png" class="aboutusBg" />
    </div>

    <div class="aboutus-body-1">
        <div class="aboutus-yazi-10">Hakkımızda</div>

        <div class="aboutus-yazi-11"> 2023 Eylül ayında kurulmuş sanal bir kütüphanede çalışan kitap okumayı seven
            biriylerden oluşuyuruz.
        </div>

        <div class="aboutus-yazi-12">Amacımız dünyaya kitapları tanıtmak ve insan-kitap bağını güçlendirmek.
        </div>

        <div class="aboutus-yazi-13">Sonsuz maceraların kapıları aralanıyor! Sizleri kitapların büyülü dünyasına
            davet ediyoruz
        </div>

        <div class="aboutus-yazi-14"> Yılların deneyimiyle, kitapları seviyor ve sizlere her okuduğunuzda
            büyülenmenizi sağlayacak eserleri sunuyoruz
        </div>

    </div>
    <div class="aboutus-books-inbox">Books Inbox</div>
    
</div>

Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "Hakkımzda";
    <link rel="stylesheet" href="~/css/aboutusStyle.css" />
}
<div class="aboutusBg">
    <img src="~/img/AboutusBg.png" class="aboutusBg" />
</div>

<div class="aboutus-body-2">
    <div class="aboutus-yazi-20">Bize Ulaşın</div>

    <div class="aboutus-yazi-21">
        <p> Size nasıl yardımcı olabiliriz? Sorularınızı, geri bildirimlerinizi veya herhangi bir konuyu bize
            iletmek
            için
            buradayız. Bizimle iletişime geçmek için iletişim formunu doldurabilirsiniz.</p>
    </div>
</div>


<div class="aboutus-body-3">
    <form action="#" method="post">
         <div class="kutucuk">
            <label class="label1"><b>Adınız Soyadını :</b></label>
            <input class="text1" type="text" id="adsoyad" name="Username" placeholder="Adınızı Giriniz">

            <label class="label2"><b>Email Adresiniz :</b></label>
            <input class="text2" type="email" id="email" placeholder="example@gmail.com">

            <label class="label3"><b>Geri Bildiriminiz :</b></label>
            <textarea class="text3" id="mesaj" type="" placeholder="..."></textarea>
</div>
<div class="button">
    <input type="button" value="Gönder" id="gonderButton">
</div>
<div class="aboutus-books-inbox">Books Inbox</div>
<script>
    // Gönder düğmesine tıklanınca e-posta bağlantısını oluştur
    document.getElementById("gonderButton").addEventListener("click", function () {
        var adsoyad = document.getElementById("adsoyad").value;
        var email = document.getElementById("email").value;
        var mesaj = document.getElementById("mesaj").value;

        var subject = "Geri Bildirim"; // E-posta konusu

        // E-posta içeriği oluştur
        var body = "Merhaba,\n\nAd Soyad: " + adsoyad + "\nE-posta: " + email + "\n\nKonu: " + mesaj + "\n";

        // E-posta bağlantısını oluştur
        var mailtoLink = "mailto:destek@example.com?subject=" + encodeURIComponent(subject) + "&body=" + encodeURIComponent(body);

        // E-posta bağlantısını aç
        window.location.href = mailtoLink;
    });
</script>
</form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
    <link rel="stylesheet" href="~/css/homeStyle.css" />
}
<div class="homeBg">
            <img src="../img/homeBg.png" class="homeBg" />
        </div>

 <!--Body-->
<div class="home-page">
        
        <div class="kitaplar">
            <a asp-controller="Book" asp-action="Detail" asp-route-id="3"><img class="kitap-1" src="../img/kitap-1.png" /></a>
            <a asp-controller="Book" asp-action="Detail" asp-route-id="9"><img class="kitap-2" src="../img/kitap-2.png" /></a>
            <a asp-controller="Book" asp-action="Detail" asp-route-id="10"><img class="kitap-3" src="../img/kitap-3.png" /></a>
            <a asp-controller="Book" asp-action="Detail" asp-route-id="12"><img class="kitap-4" src="../img/kitap-4.png" /></a>
            <a asp-controller="Book" asp-action="Detail" asp-route-id="14"><img class="kitap-5" src="../img/kitap-5.png" /></a>
            <a asp-controller="Book" asp-action="Detail" asp-route-id="15"><img class="kitap-6" src="../img/kitap-6.png" /></a>
            <a asp-controller="Book" asp-action="Detail" asp-route-id="16"><img class="kitap-7" src="../img/kitap-7.png" /></a>
        </div>

        <div class="home-body">
            <div class="books-inbox">
                <span>
                    <span class="books-inbox-span">Books</span>
                    <span class="books-inbox-span2">Inbox</span>
                </span>
            </div>
            <div class="home-yazi-1">
                <span>
                    <span class="home-yazi-11">Sonsuz maceraların kapıları aralanıyor!
                        <br /><br />
                        Sizleri kitapların büyülü dünyasına
                    </span>
                    <span class="home-yazi-12"><a asp-controller="Book" asp-action="Index" >davet ediyoruz</a>
                    </span>
                </span>
            </div>
            <div class="home-yazi-2">
                <span>
                    <span class="home-yazi-21">En sevdiğiniz </span>
                    <span class="home-yazi-22">yazarların eserleri<br /></span>
                    <span class="home-yazi-23">yeni keşfedeceğiniz</span>
                    <span class="home-yazi-24"> yazarlarla dolu geniş koleksiyonumuzla
                        <br />size eşlik etmek için buradayız
                    </span>
                </span>
            </div>
        </div>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/headerstyle.css">
    <link rel="stylesheet" href="~/css/footerStyle.css" />
    <link rel="stylesheet" href="~/Books_Inbox.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/favicon.jpg" type="image/jpeg" />
</head>
<body>
    <header>
     <div class="header-group">
        <div class="header-bg"></div>
        <div class="header">
            <div class="menu">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="item">Ana Sayfa</a>
                <a asp-area="" asp-controller="Book" asp-action="Index"  class="item">Kitaplar</a>
                <a asp-area="" asp-controller="Writer" asp-action="Index"  class="item">Yazarlar</a>
                <a class="item" asp-area="" asp-controller="Home" asp-action="AboutUs">Hakkımızda</a>
                <a asp-area="" asp-controller="Home" asp-action="ContactUs" class="item">Bize Ulaşın</a>
                
                
            </div> 
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <img class="logo"  src="~/img/logo.png" alt="Logo" />
            </a>
        </div>
    </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           <div class="footer">
        <div class="menuf">
            <a href="https://facebook.com">
                <img class="facebook" src="~/img/facebook.png" alt="facebook logo" />
            </a>
            <a href="https://instagram.com">
                <img class="instagram" src="~/img/instagram.png" alt="instagram logo" />
            </a>
            <a href="https://x.com">
                <img class="twitter" src="~/img/twitter.png" alt="twitter logo" />
            </a>
            <a href="https://whatsapp.com">
                <img class="whatsapp" src="~/img/whatsapp.png" alt="whatsapp logo" />
            </a>
        </div>
        <div class="copy">
            &copy;2023 Muhammed Yusufoğlu - Tüm Hakları Saklıdır
        </div>
    </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/_framework/aspnetcore-browser-refresh.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Writer/Detail.cshtml
@model WriterDetailViewModel

@{
    ViewData["Title"] = @Model.Writer.Name;
    <link rel="stylesheet" href="~/css/footerStyle.css" />
    <link rel="stylesheet" href="~/css/booksStyle.css" />
    <link rel="stylesheet" href="~/css/sliderStyle.css" />
}
<br>
<br>
<div class="border p-3 mt-4">
    <h1>@Model.Writer.Name </h1>


    <div class="row">
        <div class="col-md-6">
            <img src="@Url.Content("~/img/Yazarlar/" +@Model.Writer.ImageName)" alt="Writer Image"
                class="card-img viewimg">

        </div>


        <ul>
            <div> Ad: @Model.Writer.Name </div>
            <br>
            <div>
                <br>
                <p>Doğum Tarihi: @Model.Writer.BrithDataTime.Year </p>
                <br>
                <p>Ölüm Tarihi: @Model.Writer.DeathDataTime.Year </p>

            </div>
            <a asp-controller="Writer" asp-action="Index"><button class="ViewBtn">Geri</button></a>

        </ul>
    </div>
    @if (Model.Book != null)
    {
        <div class="image-content">
            <span class="overlay"></span>
            <div class="card-image">

                <img src="@Url.Content("~/img/" +@Model.Book.ImageName)" alt="Book Image" class="card-img viewimg">
            </div>
        </div>
        <div class="card-content">
            <h2 class="name">@Model.Book.Name</h2>
            <p class="descreption">@Model.Book.WriterName</p>
            <a asp-controller="Book" asp-action="Detail" asp-route-id="@Model.Book.ID"><button
                    class="ViewBtn">Görüntüle</button></a>

        </div>

        <br>

        <br>

        <br>

        <br>

        <br>

        <br>

        <br>

        <br>

        <br>
    }

Views/Writer/Index.cshtml
@model IEnumerable<Writer>
@{
    ViewData["Title"] = "Yazarlar";
    
    <link rel="stylesheet" href="~/css/booksStyle.css" />
    <link rel="stylesheet" href="~/css/sliderStyle.css" />
    <link rel="stylesheet" href="~/css/swiper-bundle.min.css">
}

<!--Body1-->
<div class="books-body-1">
    <div class="books-yazi-1">Ünlü Yazarlar</div>
</div>

<!--slider-->
<div class="slide-container swiper">
    <div class="slide-content">
        <div class="card-wrapper swiper-wrapper">
            <!--#region card swiper-slides  -->
            <!--01-->
            @foreach (var obj in Model)
            {
                <div class="card swiper-slide">
                    <div class="image-content">
                        <span class="overlay"></span>
                        <div class="card-image">
                            <img src="@Url.Content("~/img/Yazarlar/" +@obj.ImageName)" alt="Yazar Image" class="card-img">
                        </div>
                    </div>
                    <div class="card-content">
                        <h5 class="name">@obj.Name</h5>
                        
                        <button class="ViewBtn"> <a asp-controller="Writer" asp-action="Detail" asp-route-id="@obj.ID">Görüntüle</a></button>
                    </div>
                </div>
            }
            <!-- endregion -->
        </div>
    </div>
    <div class="swiper-button-next swiper-navBtn"></div>
    <div class="swiper-button-prev swiper-navBtn"></div>
    <div class="swiper-pagination"></div>
</div>


<script src="../js/swiper-bundle.min.js"></script>